selfservice:
  default_browser_return_url: https://auth.dyser.space
  flows:
    settings:
      privileged_session_max_age: 1m
      after:
        profile:
          hooks:
            - hook: verify
      ui_url: https://auth.dyser.space/settings
    verification:
      after:
        default_browser_return_url: https://auth.dyser.space/
      ui_url: https://auth.dyser.space/verify
    logout:
      after:
        default_browser_return_url: https://auth.dyser.space/auth/login
    login:
      lifespan: 10m
      ui_url: https://auth.dyser.space/auth/login
    registration:
      lifespan: 10m
      after:
        password:
          hooks:
            - hook: session
      ui_url: https://auth.dyser.space/auth/registration
    error:
      ui_url: https://auth.dyser.space/error
  whitelisted_return_urls:
    - https://auth.dyser.space/
log:
  level: debug
secrets:
  default:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
serve:
  public:
    base_url: https://auth.dyser.space/.ory/kratos/public/
  admin:
    base_url: http://kratos:4434/
hashers:
  argon2:
    parallelism: 1
    memory: 131072
    iterations: 2
    salt_length: 16
    key_length: 16
identity:
  default_schema_url: file:///etc/config/kratos/identity.traits.schema.json
courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true